<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* tr-car-rentals/views/admin/receipts/index.html */
class __TwigTemplate_53c2df434e13bbb3b7f685b74e5a68ae extends Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->blocks = [
            'content' => [$this, 'block_content'],
        ];
    }

    protected function doGetParent(array $context)
    {
        // line 1
        return "_layout_admin_fomantic.html";
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $this->parent = $this->loadTemplate("_layout_admin_fomantic.html", "tr-car-rentals/views/admin/receipts/index.html", 1);
        $this->parent->display($context, array_merge($this->blocks, $blocks));
    }

    // line 3
    public function block_content($context, array $blocks = [])
    {
        $macros = $this->macros;
        // line 4
        echo "<section style=\"padding-top: 30px; padding-bottom: 70px;\">
    <h2 class=\"ui header\">Car Rental Receipts</h2>
    <div class=\"ui message\">
        <ul>
        <li>Receipts can be generated multiple times for the same booking. Existing receipts will be voided and replaced with the most recent generated receipt for a booking.</li>
        <li>Receipts can be generated by clicking on \"Confirm\" action in the manager's bookings dashboard.</li>
        <li>Points to the table \"car_rentals_receipts\".</li>
        </ul>
      </div>
    
    <div class=\"ui long scrolling container\">
        <table class=\"ui first last head stuck unstackable celled single line table\" style=\"z-index: 1;\">
            <thead>
                <tr>
                    <th>Receipt Number</th>
                    <th>Issue Date</th>
                    <th>Customer Name</th>
                    <th>Customer Email</th>
                    <th>Customer Phone</th>
                    <th>Car Model</th>
                    <th>Pickup Date</th>
                    <th>Return Date</th>
                    <th>Pickup Location</th>
                    <th>Return Location</th>
                    <th>Rental Days</th>
                    <th>Rental Fee</th>
                    <th>Insurance Fee</th>
                    <th>GPS Fee</th>
                    <th>Subtotal</th>
                    <th>Tax</th>
                    <th>Total Amount</th>
                    <th>Payment Method</th>
                    <th>Card Last Four</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                ";
        // line 41
        $context['_parent'] = $context;
        $context['_seq'] = twig_ensure_traversable(($context["rows"] ?? null));
        $context['_iterated'] = false;
        foreach ($context['_seq'] as $context["_key"] => $context["row"]) {
            // line 42
            echo "                <tr>
                    <td>";
            // line 43
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "receipt_number", [], "any", false, false, false, 43), "html", null, true);
            echo "</td>
                    <td>";
            // line 44
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "issued_date", [], "any", false, false, false, 44), "html", null, true);
            echo "</td>
                    <td>";
            // line 45
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "customer_name", [], "any", false, false, false, 45), "html", null, true);
            echo "</td>
                    <td>";
            // line 46
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "customer_email", [], "any", false, false, false, 46), "html", null, true);
            echo "</td>
                    <td>";
            // line 47
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "customer_phone", [], "any", false, false, false, 47), "html", null, true);
            echo "</td>
                    <td>";
            // line 48
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "car_model", [], "any", false, false, false, 48), "html", null, true);
            echo "</td>
                    <td>";
            // line 49
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "pickup_date", [], "any", false, false, false, 49), "html", null, true);
            echo "</td>
                    <td>";
            // line 50
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "return_date", [], "any", false, false, false, 50), "html", null, true);
            echo "</td>
                    <td>";
            // line 51
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "pickup_location", [], "any", false, false, false, 51), "html", null, true);
            echo "</td>
                    <td>";
            // line 52
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "return_location", [], "any", false, false, false, 52), "html", null, true);
            echo "</td>
                    <td>";
            // line 53
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "rental_days", [], "any", false, false, false, 53), "html", null, true);
            echo "</td>
                    <td>";
            // line 54
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "rental_fee", [], "any", false, false, false, 54), "html", null, true);
            echo "</td>
                    <td>";
            // line 55
            (( !(null === twig_get_attribute($this->env, $this->source, $context["row"], "insurance_fee", [], "any", false, false, false, 55))) ? (print (twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "insurance_fee", [], "any", false, false, false, 55), "html", null, true))) : (print ("-")));
            echo "</td>
                    <td>";
            // line 56
            (( !(null === twig_get_attribute($this->env, $this->source, $context["row"], "gps_fee", [], "any", false, false, false, 56))) ? (print (twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "gps_fee", [], "any", false, false, false, 56), "html", null, true))) : (print ("-")));
            echo "</td>
                    <td>";
            // line 57
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "subtotal", [], "any", false, false, false, 57), "html", null, true);
            echo "</td>
                    <td>";
            // line 58
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "tax", [], "any", false, false, false, 58), "html", null, true);
            echo "</td>
                    <td>";
            // line 59
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "total_amount", [], "any", false, false, false, 59), "html", null, true);
            echo "</td>
                    <td>";
            // line 60
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "payment_method", [], "any", false, false, false, 60), "html", null, true);
            echo "</td>
                    <td>";
            // line 61
            (( !(null === twig_get_attribute($this->env, $this->source, $context["row"], "card_last_four", [], "any", false, false, false, 61))) ? (print (twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "card_last_four", [], "any", false, false, false, 61), "html", null, true))) : (print ("-")));
            echo "</td>
                    <td>
                        <a href=\"/framework/admin/car-rentals/receipts/pdf/";
            // line 63
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["row"], "receipt_number", [], "any", false, false, false, 63), "html", null, true);
            echo "\" class=\"ui button\">View PDF</a>
                    </td>
                </tr>
                ";
            $context['_iterated'] = true;
        }
        if (!$context['_iterated']) {
            // line 67
            echo "                <tr>
                    <td colspan=\"20\" class=\"center aligned\">No receipts found</td>
                </tr>
                ";
        }
        $_parent = $context['_parent'];
        unset($context['_seq'], $context['_iterated'], $context['_key'], $context['row'], $context['_parent'], $context['loop']);
        $context = array_intersect_key($context, $_parent) + $_parent;
        // line 71
        echo "            </tbody>
        </table>
    </div>
</section>
";
    }

    public function getTemplateName()
    {
        return "tr-car-rentals/views/admin/receipts/index.html";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  192 => 71,  183 => 67,  174 => 63,  169 => 61,  165 => 60,  161 => 59,  157 => 58,  153 => 57,  149 => 56,  145 => 55,  141 => 54,  137 => 53,  133 => 52,  129 => 51,  125 => 50,  121 => 49,  117 => 48,  113 => 47,  109 => 46,  105 => 45,  101 => 44,  97 => 43,  94 => 42,  89 => 41,  50 => 4,  46 => 3,  35 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("", "tr-car-rentals/views/admin/receipts/index.html", "/mnt/BLOCKSTORAGE/home/359206.cloudwaysapps.com/srxrwayjxu/public_html/modules/tr-car-rentals/views/admin/receipts/index.html");
    }
}
